project:
  type: book
  
book:
  title: "Cartographie avec R"
  author:
    - name: Timothée Giraud
      orcid: 0000-0001-5679-6536
      email: timothee.giraud@cnrs.fr
      url: https://rgeomatic.hypotheses.org
      affiliations:
        - id: 1
          name: RIATE
          url: https://riate.cnrs.fr
        - id: 2
          name: INED
          url: https://www.ined.fr/
    - name: Bénédicte Garnier
      url: https://www.ined.fr/fr/recherche/chercheurs/Garnier+B%C3%A9n%C3%A9dicte
      affiliations:
        - id: 1
          name: INED
          url: https://www.ined.fr/
  date: "23 septembre 2022"
  search: false
  repo-url: https://github.com/rcarto/ined2022/
  sharing: [twitter]
  cover-image: img/globe-africa-solid.svg
  page-footer: 
    left: "[![CreativeCommonsLicense](img/by-nc-sa.png)](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
  favicon: img/globe-africa-solid.svg
  twitter-card: true
  creator: "rgeomatic"
  open-graph: true
  chapters:
    - index.qmd
    - 01_ecosysteme_spatial.qmd
    - 02_donnees_vectorielles.qmd
    - 03_cartographie.qmd
    - 04_references.qmd

bibliography: references.bib

lang: fr

csl: "universite-de-montreal-apa.csl"


format:
  html:
    callout-appearance: simple
    callout-icon: false
    theme:
      light: cosmo
      dark: cyborg

